2992656 option codes
thejacer87/commerce_canadapost pull request #10
Opened 2018-08-15 19:17 UTC by thejacer87

D.O issue [here](https://www.drupal.org/project/commerce_canadapost/issues/2992656)

2018-08-17 12:21 UTC, krystalcode requested changes

2018-08-17 12:21 UTC, krystalcode commented on src/Plugin/Commerce/ShippingMethod/CanadaPost.php
> +      ],
**OPTIONAL CHANGE REQUEST**

I think these could be made available at the PHP SDK level. So if they add more options we don't have to make changes to the module. You can change `Rating::VALID_OPTION_CODES` to be:

```
const VALID_OPTION_CODES = [
  'SO' => 'Signature (SO),
  'PA18' => 'Proof of Age Required - 18 (PA18),
  // ...
];
```

and use `array_keys(Rating::VALID_OPTION_CODES)` when you want to get only the codes.

2018-08-17 12:21 UTC, krystalcode commented on src/Plugin/Commerce/ShippingMethod/CanadaPost.php
> +        "Select which options to add to the get rates request. <strong>NOTE:</strong> Some options conflict with each other (eg. PA18, PA19 and DNS), so be sure to check the logs if the rates fail to
**OPTIONAL CHANGE REQUEST**

We can make the text less technical; a store manager may not understand what a "get rates request" is. What about "Select which options to add when calculating the shipping rates.".

2018-08-17 12:21 UTC, krystalcode commented on src/Plugin/Commerce/ShippingMethod/CanadaPost.php
> +    return $this->ratingService->getRates($shipment, ['debug' => FALSE, 'option_codes' => $option_codes]);
**CHANGE REQUEST**

*Coding standards*

Let's conform with line length standards:

```
return $this->ratingService->getRates(
  $shipment,
  [
    'debug' => FALSE,
    'option_codes' => $this->configuration['option_codes']['codes'],
  ]
);
```

2018-08-17 12:21 UTC, krystalcode commented on src/Plugin/Commerce/ShippingMethod/CanadaPost.php
> +    $this->configuration['option_codes']['codes'] = $values['option_codes']['codes'];
**CHANGE REQUEST**

It is ok that you need to have `codes` under `option_codes` in the form so that you can put them in a `details` container, however there is no reason to have 2 levels in the actual configuration holding the values. The following would do:

`$this->configuration['option_codes'] = $values['option_codes']['codes'];`

2018-08-17 18:49 UTC, krystalcode commented
@thejacer87 All good. We will need however to update `composer.json` to require the new version we're going to release for the PHP SDK. Otherwise the module will not work with previous version.

2018-08-17 21:02 UTC, krystalcode approved these changes

2018-10-05 17:41 UTC, thejacer87 commented
merge in the drupal.org repo: https://cgit.drupalcode.org/commerce_canadapost/commit/?id=07be4aebc77e1f74a823b3dee15e5dbbc651e8d5

2018-10-05 17:41 UTC, closed without merging